version: '3.8'

services:
  # PostgresSQL Database Service
  db:
    image: postgres:14-alpine
    container_name: event-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: event-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Expose db port for local debugging (optional)
    networks:
      - event-network

  # Spring Boot Backend Service
  backend:
    container_name: event-backend
    build:
      context: ./backend # Path to backend Dockerfile
    depends_on:
      - db
    environment:
      # Tell Spring to connect to the 'db' service
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/event-db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      # Pass in the JWT secret from an env file for better security
      JWT_SECRET: ${JWT_SECRET:-mysecretkeymysecretkeymysecretkeymysecretkeymysecretkey}
    ports:
      - "8080:8080" # Expose for direct API testing (optional)
    networks:
      - event-network

  # React Frontend + NGINX Proxy Service
  frontend:
    container_name: event-frontend-proxy
    build:
      context: ./frontend # Path to frontend Dockerfile
    ports:
      - "80:80" # Expose NGINX on port 80 (http://localhost)
    depends_on:
      - backend
    networks:
      - event-network

# Define the network
networks:
  event-network:
    driver: bridge

# Define the persistent volume for the database
volumes:
  postgres_data: